theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
completion-trigger-len = 1
lsp.display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.g]
t = ":format"

[keys.normal.space]
x = ":buffer-close"
# e = [":new", ":insert-output lf -selection-path=/dev/stdout", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":redraw"]
o = "file_picker_in_current_buffer_directory"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
