theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
completion-trigger-len = 1
# lsp.display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "select_line_above"
# ret = "goto_file"

[keys.normal.g]
t = ":format"
ret = ["goto_file", "goto_last_modified_file", ":buffer-close!"]
F = ["select_line_below", "yank", "select_all", "delete_selection_noyank", "paste_after", "select_line_below", ":pipe xargs -I {} sh ~/.config/helix/sort-find.sh {}", "goto_file_start"]

[keys.normal.space]
x = ":buffer-close"
X = ":buffer-close!"
e = [":new", ":insert-output sh ~/.config/helix/sort-find.sh .", "goto_file_start"]
o = "file_picker_in_current_buffer_directory"
### You can use this if you like to ###
# e = [":new", ":insert-output lf -selection-path=/dev/stdout", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":redraw"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode
