theme = "material_darker"

[editor]
line-number = "relative"
bufferline = "multiple"
completion-trigger-len = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
x = ":buffer-close"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
